let url="http://localhost:3000/fruits/";
//Define Fruit Object type with required properties like id, name, image, unit and price
type Fruit = {
    Id: number | string,
    name: string,
    image: any,
    unit: string,
    price: number,
};

// Note:As per test requirement, Fruits API should be running on port 3000
function getFruits() {
    //Return the promise returned by the fetch() method
    let promiseObj = fetch(url);

    //Successful promise callback function should convert the response body text to json object and return the promise as result.
    let promiseJson= promiseObj.then((response)=>response.json());

    //Returned successful promise callback should call `transform()` method by passing the json object as argument
     transform(promiseJson);
     
     return promiseObj
}

//Inside transform() function, iterate the json data passed as parameter.
//Then transform each fruit to transformedFruit object that mirrors Fruit type 
function transform(JsonData:any) {
    //call showFruit() function for each transformedFruit object
   let getData = JsonData.then((data :any)=>data.forEach((item :any)=>{
        console.log(item.name + "----->>" + item.price + "----->>" + item.unit)

        let transformedFruit: Fruit = {
          Id: item.id,
          name: item.name,
          image: item.image,
          unit: item.unit,
          price: item.price
      };
      showFruit(transformedFruit);
  }));
  
}

//Inside showFruit() function, pass transformedFruit object as parameter
function showFruit(transformedFruit : Fruit) {
    //display each transformedFruit as card by creating HTML code as string and appending it to the div container
           let div:any = document.getElementById("container"); 
            let card =  `<div class="card text-center m-3 pb-4 col-lg-2">
            <img src="${transformedFruit.image}" height=150 width=150 class="m-5 my-3">
            <h4>${transformedFruit.name}</h4>
            <h5 class="text-secondary" >Price : $${transformedFruit.price} per lb</h5>              
            </div>`;
            div.innerHTML += card;
}

//compiler error for "module" will be resolved once node_modules folder is generated by giving 'npm install' command in the terminal
// do not delete the code given below, it is written to export the functions to be tested
module.exports = {
    getFruits
}
